const api = [
    {
        "empresa":"Facebook",
        "vaga":"Estagio-001",
        "requisitos":"Cursando",
        "palavrachave":"001",
        "localizacao":"PE-Recife"
    },
    {
        "empresa":"Facebook",
        "vaga":"Estagio-002",
        "requisitos":"Cursando",
        "palavrachave":"002",
        "localizacao":"PE-Recife"
    },
    {
        "empresa":"Facebook",
        "vaga":"Estagio-003",
        "requisitos":"Cursando",
        "palavrachave":"003",
        "localizacao":"PE-Recife"
    },
    {
        "empresa":"Facebook",
        "vaga":"Estagio-004",
        "requisitos":"Cursando",
        "palavrachave":"004",
        "localizacao":"PE-Recife"
    },
    {
        "empresa":"Facebook",
        "vaga":"Estagio-005",
        "requisitos":"Cursando",
        "palavrachave":"005",
        "localizacao":"PE-Recife"
    },
    {
        "empresa":"Facebook",
        "vaga":"Estagio-006",
        "requisitos":"Cursando",
        "palavrachave":"006",
        "localizacao":"PE-Recife"
    },
    {
        "empresa":"Facebook",
        "vaga":"Estagio-007",
        "requisitos":"Cursando",
        "palavrachave":"007",
        "localizacao":"PE-Recife"
    },
    {
        "empresa":"Facebook",
        "vaga":"Estagio-008",
        "requisitos":"Cursando",
        "palavrachave":"008",
        "localizacao":"PE-Recife"
    },
    {
        "empresa":"Facebook",
        "vaga":"Estagio-009",
        "requisitos":"Cursando",
        "palavrachave":"009",
        "localizacao":"PE-Recife"
    }
]

export default api;