const api = [
    {
        "empresa":"facebook",
        "vaga":"estagio1",
        "requisitos":"Cursando",
        "palavrachave":"001",
        "localizacao":"PE-Recife"
    },
    {
        "empresa":"facebook",
        "vaga":"estagio2",
        "requisitos":"Cursando",
        "palavrachave":"002",
        "localizacao":"PE-Recife"
    },
    {
        "empresa":"facebook",
        "vaga":"estagio3",
        "requisitos":"Cursando",
        "palavrachave":"003",
        "localizacao":"PE-Recife"
    },
    {
        "empresa":"facebook",
        "vaga":"estagio4",
        "requisitos":"Cursando",
        "palavrachave":"004",
        "localizacao":"PE-Recife"
    },
    {
        "empresa":"facebook",
        "vaga":"estagio5",
        "requisitos":"Cursando",
        "palavrachave":"005",
        "localizacao":"PE-Recife"
    },
    {
        "empresa":"facebook",
        "vaga":"estagio6",
        "requisitos":"Cursando",
        "palavrachave":"006",
        "localizacao":"PE-Recife"
    },
    {
        "empresa":"facebook",
        "vaga":"estagio7",
        "requisitos":"Cursando",
        "palavrachave":"007",
        "localizacao":"PE-Recife"
    },
    {
        "empresa":"facebook",
        "vaga":"estagio8",
        "requisitos":"Cursando",
        "palavrachave":"008",
        "localizacao":"PE-Recife"
    },
    {
        "empresa":"facebook",
        "vaga":"estagio9",
        "requisitos":"Cursando",
        "palavrachave":"009",
        "localizacao":"PE-Recife"
    }
]

export default api;