const nota = [
    {
        "empresa":"facebook",
        "vaga":"estagio",
        "requisitos":"Cursando",
        "palavras-chave":"001",
        "localizacao":"PE-Recife"
    },
    {
        "empresa":"facebook",
        "vaga":"estagio",
        "requisitos":"Cursando",
        "palavras-chave":"002",
        "localizacao":"PE-Recife"
    },
    {
        "empresa":"facebook",
        "vaga":"estagio",
        "requisitos":"Cursando",
        "palavras-chave":"003",
        "localizacao":"PE-Recife"
    },
    {
        "empresa":"facebook",
        "vaga":"estagio",
        "requisitos":"Cursando",
        "palavras-chave":"004",
        "localizacao":"PE-Recife"
    },
    {
        "empresa":"facebook",
        "vaga":"estagio",
        "requisitos":"Cursando",
        "palavras-chave":"005",
        "localizacao":"PE-Recife"
    },
    {
        "empresa":"facebook",
        "vaga":"estagio",
        "requisitos":"Cursando",
        "palavras-chave":"006",
        "localizacao":"PE-Recife"
    },
    {
        "empresa":"facebook",
        "vaga":"estagio",
        "requisitos":"Cursando",
        "palavras-chave":"007",
        "localizacao":"PE-Recife"
    },
    {
        "empresa":"facebook",
        "vaga":"estagio",
        "requisitos":"Cursando",
        "palavras-chave":"008",
        "localizacao":"PE-Recife"
    },
    {
        "empresa":"facebook",
        "vaga":"estagio",
        "requisitos":"Cursando",
        "palavras-chave":"009",
        "localizacao":"PE-Recife"
    }
]

export default nota;